import { ROLES } from '@/utils/user'

export default {
  id: 'wndgur2',
  email: 'wndgur76@naver.com',
  name: '김민수',
  nickname: 'KIMMS',
  memberRole: ROLES.agent,
  isOAuth: false,
  favorites: {
    houseInfos: [
      {
        id: 1,
        name: '테헤란 아이파크',
        dongName: '서초동',
        address: '서울특별시 강남구 테헤란로 311',
        houseType: '아파트',
        houseDealType: '매매',
        date: '2021-10-01',
        dong: 3,
        floor: 10,
        commentN: 3,
        liked: false,
        price: 185550000,
        area: 84.5,
      },
      {
        id: 2,
        name: '역삼 멀티캠퍼스',
        dongName: '서초동',
        address: '서울특별시 강남구 테헤란로 333',
        houseType: '아파트',
        houseDealType: '매매',
        date: '2024-11-21',
        dong: 1,
        floor: 20,
        commentN: 312,
        liked: false,
        price: 1044000000,
        area: 2085.5,
      },
    ],
    houseDeals: [
      {
        id: 1,
        area: '84.98',
        phone: '02-2051-1234',
        date: '2021-10-01',
        floor: 10,
        price: 1000000,
        likedN: 5,
        liked: false,
        houseInfo: {
          id: 1,
          name: '테헤란 아이파크',
          dongName: '서초동',
          address: '서울특별시 강남구 테헤란로 311',
          houseType: '아파트',
          date: '2021-10-01',
          dong: 3,
          floor: 10,
          commentN: 3,
          liked: false,
        },
      },
    ],
  },
  articles: [],
}
